version: '3'

services:
  backend: 
    build:
      context: .
    container_name: tc-backend
    # env_file:
    #   - .env
    ports: 
      - '8080:8080'
    volumes:
      - ./data:/app/data
      - ./static/media:/app/static/media
    restart: on-failure
    # network_mode: host
    # command: gunicorn -c config/gunicorn.py app:app
  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - ./data/redis:/app/data
