#!/bin/bash

# This file is created by "eslint-pre-commit-hook" NPM library.
# UNLESS YOU YOU'RE SURE WHAT YOU'RE DOING, DON'T EDIT THIS FILE MANUALLY!
#
# If there was an older version, it's been renamed to "pre-commit--old".

make prospector
RESULT=$?
[ $RESULT -ne 0 ] && exit 1
exit 0
