FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements/requirements_base.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

RUN flask db upgrade

EXPOSE 8080

CMD [ "gunicorn", "-c" , "config/gunicorn.py", "run:app"]
