FROM arm64v8/python:3.10-slim

WORKDIR /app

COPY requirements/requirements_base.txt requirements.txt
RUN apt-get update
RUN apt-get -y install gcc python3-dev
RUN pip3 install -r requirements.txt


COPY . .

RUN python data/create_db.py
RUN flask db upgrade
RUN python data/create_fixtures.py


EXPOSE 8080

CMD [ "flask", "run" , "--host", "0.0.0.0", "--port", "8080"]
