"""Init5

Revision ID: 006c4772c73c
Revises: 1fa651321351
Create Date: 2023-10-04 17:23:56.736101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006c4772c73c'
down_revision = '1fa651321351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_order', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    # ### end Alembic commands ###
