"""remove password col from users table

Revision ID: 019693b33c62
Revises: a8c5a14bc876
Create Date: 2023-08-07 14:58:39.196681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019693b33c62'
down_revision = 'a8c5a14bc876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
