"""Database creation

Revision ID: 1615ec360696
Revises: 7d291cd39a18
Create Date: 2023-08-01 06:21:03.627727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1615ec360696'
down_revision = '7d291cd39a18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
