"""First2 commit

Revision ID: 2e3bc50f8655
Revises: e34322fe8a5b
Create Date: 2023-08-01 16:39:55.319547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e3bc50f8655'
down_revision = 'e34322fe8a5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
