"""empty message

Revision ID: 305158487226
Revises: 90fa2b088de3
Create Date: 2023-12-16 16:31:38.905712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305158487226'
down_revision = '90fa2b088de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('post', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_user_info')
    # ### end Alembic commands ###
