"""user picture5

Revision ID: 4eb664a59c17
Revises: c4e1a82b4b60
Create Date: 2023-10-01 08:47:38.559471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eb664a59c17'
down_revision = 'c4e1a82b4b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_picture',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_picture')
    # ### end Alembic commands ###
