"""First commit

Revision ID: 9e977b97b963
Revises: bacc5a59d8b6
Create Date: 2023-08-01 10:03:54.018499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e977b97b963'
down_revision = 'bacc5a59d8b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=50), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
