"""First commit

Revision ID: bacc5a59d8b6
Revises: b58b99068292
Create Date: 2023-08-01 10:03:15.612850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bacc5a59d8b6'
down_revision = 'b58b99068292'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=50), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
