"""First commit

Revision ID: de273c330f4b
Revises: 9e977b97b963
Create Date: 2023-08-01 16:30:57.341638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de273c330f4b'
down_revision = '9e977b97b963'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
