"""First2 commit

Revision ID: e34322fe8a5b
Revises: de273c330f4b
Create Date: 2023-08-01 16:32:51.694752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34322fe8a5b'
down_revision = 'de273c330f4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
