"""First2 commits

Revision ID: ee7f7bdab7a7
Revises: 2e3bc50f8655
Create Date: 2023-08-01 16:40:39.631224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7f7bdab7a7'
down_revision = '2e3bc50f8655'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
