name: Run Prospector & Pytest

on:
  pull_request:
    branches: [development]
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/requirements.txt ]; then pip install -r requirements/requirements.txt; fi
      - name: Run Prospector
        run: |
          prospector --profile=config/prospector.yaml
        continue-on-error: false
      - name: Test with pytest
        run: |
          echo 'not implemented yet'
        continue-on-error: false
